CREATE TYPE roles AS ENUM('ROLE_ADMIN', 'ROLE_CULINARY_JUDGE', 'ROLE_MUSICAL_JUDGE');

CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    username VARCHAR(24) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    role roles NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP
);